"""Version identifiers embedded in public artifacts."""

ENGINE_VERSION = "2.0.0"
CONTROLLER_API_VERSION = 2
SCENARIO_GENERATOR_VERSION = 2
REPLAY_VERSION = 2
CALIBRATION_VERSION = 3
TOURNAMENT_FORMAT_VERSION = 3
